apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment-sm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-mesh
  template:
    metadata:
      labels:
        app: apache-mesh
    spec:
      containers:
      - name: apache
        image: docker.io/bitnami/apache:2.4.57-debian-11-r24
        ports:
        - containerPort: 80
      - name: metrics
        image: docker.io/bitnami/apache-exporter:0.13.4-debian-11-r1
        command:
          - /bin/apache_exporter
          - '--scrape_uri'
          - http://status.localhost:8080/server-status/?auto
        ports:
          - containerPort: 9117
            name: metrics
            protocol: TCP
