apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  labels:
    app: apache-mesh
    release: prometheus-operator
  name: prometheus-apache
#  namespace: cz-istio
spec:
  endpoints:
  - path: /metrics
    port: metrics
    scheme: https
    enableHttp2: false
    tlsConfig:
      caFile: /etc/istio-certs/root-cert.pem
      certFile: /etc/istio-certs/cert-chain.pem
      keyFile: /etc/istio-certs/key.pem
      insecureSkipVerify: true
#  namespaceSelector:
#    matchNames:
#    - cz-istio
  selector:
    matchLabels:
      app: apache-mesh
